import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ReduxProvider from './redux/provider'
import Header from './components/header'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Clothes-e-commerce',
  description: 'Generated by create next app',
  icons: "https://static.vecteezy.com/system/resources/previews/014/341/287/original/red-winter-hat-free-png.png"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Header/>
          <div className="bg-dark">
            {children}
          </div>
          <Footer/>
        </ReduxProvider>
      </body>
    </html>
  )
}